//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.12 at 05:23:43 PM CEST 
//


package org.w3._2003._05.soap_envelope;

/*
 * #%L
 * ====================================================
 *   _____                _     ____  _____ _   _ _   _
 *  |_   _|_ __ _   _ ___| |_  / __ \|  ___| | | | | | |
 *    | | | '__| | | / __| __|/ / _` | |_  | |_| | |_| |
 *    | | | |  | |_| \__ \ |_| | (_| |  _| |  _  |  _  |
 *    |_| |_|   \__,_|___/\__|\ \__,_|_|   |_| |_|_| |_|
 *                             \____/
 * 
 * =====================================================
 * 
 * Fachhochschule Hannover 
 * (University of Applied Sciences and Arts, Hannover)
 * Faculty IV, Dept. of Computer Science
 * Ricklinger Stadtweg 118, 30459 Hannover, Germany
 * 
 * Email: trust@f4-i.fh-hannover.de
 * Website: http://trust.inform.fh-hannover.de/
 * 
 * This file is part of irond, version 0.4.1, implemented by the Trust@FHH
 * research group at the Fachhochschule Hannover.
 * 
 * irond is an an *experimental* IF-MAP 2.0 compliant MAP server written in
 * JAVA. irond supports both basic authentication and certificate-based 
 * authentication (using X.509 certificates) of MAP clients. irond is
 * maintained by the Trust@FHH group at the Fachhochschule Hannover, initial
 * developement was carried out during the ESUKOM research project.
 * %%
 * Copyright (C) 2010 - 2014 Trust@FHH
 * %%
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * #L%
 */

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.trustedcomputinggroup._2010.ifmap._2.AttachSession;
import org.trustedcomputinggroup._2010.ifmap._2.DumpRequestType;
import org.trustedcomputinggroup._2010.ifmap._2.EndSessionType;
import org.trustedcomputinggroup._2010.ifmap._2.NewSessionRequestType;
import org.trustedcomputinggroup._2010.ifmap._2.PollRequestType;
import org.trustedcomputinggroup._2010.ifmap._2.PublishRequestType;
import org.trustedcomputinggroup._2010.ifmap._2.PurgePublisherRequestType;
import org.trustedcomputinggroup._2010.ifmap._2.RenewSessionType;
import org.trustedcomputinggroup._2010.ifmap._2.ResponseType;
import org.trustedcomputinggroup._2010.ifmap._2.SearchRequestType;
import org.trustedcomputinggroup._2010.ifmap._2.SubscribeRequestType;


/**
 * <p>Java class for Body complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Body">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.trustedcomputinggroup.org/2010/IFMAP/2}newSession"/>
 *         &lt;element ref="{http://www.trustedcomputinggroup.org/2010/IFMAP/2}publish"/>
 *         &lt;element ref="{http://www.trustedcomputinggroup.org/2010/IFMAP/2}search"/>
 *         &lt;element ref="{http://www.trustedcomputinggroup.org/2010/IFMAP/2}subscribe"/>
 *         &lt;element ref="{http://www.trustedcomputinggroup.org/2010/IFMAP/2}poll"/>
 *         &lt;element ref="{http://www.trustedcomputinggroup.org/2010/IFMAP/2}purgePublisher"/>
 *         &lt;element ref="{http://www.trustedcomputinggroup.org/2010/IFMAP/2}attachSession"/>
 *         &lt;element ref="{http://www.trustedcomputinggroup.org/2010/IFMAP/2}renewSession"/>
 *         &lt;element ref="{http://www.trustedcomputinggroup.org/2010/IFMAP/2}endSession"/>
 *         &lt;element ref="{http://www.trustedcomputinggroup.org/2010/IFMAP/2}response"/>
 *         &lt;element ref="{http://www.trustedcomputinggroup.org/2010/IFMAP/2}dump"/>
 *       &lt;/choice>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Body", propOrder = {
    "newSession",
    "publish",
    "search",
    "subscribe",
    "poll",
    "purgePublisher",
    "attachSession",
    "renewSession",
    "endSession",
    "response",
    "dump"
})
public class Body {

    @XmlElement(namespace = "http://www.trustedcomputinggroup.org/2010/IFMAP/2")
    protected NewSessionRequestType newSession;
    @XmlElement(namespace = "http://www.trustedcomputinggroup.org/2010/IFMAP/2")
    protected PublishRequestType publish;
    @XmlElement(namespace = "http://www.trustedcomputinggroup.org/2010/IFMAP/2")
    protected SearchRequestType search;
    @XmlElement(namespace = "http://www.trustedcomputinggroup.org/2010/IFMAP/2")
    protected SubscribeRequestType subscribe;
    @XmlElement(namespace = "http://www.trustedcomputinggroup.org/2010/IFMAP/2")
    protected PollRequestType poll;
    @XmlElement(namespace = "http://www.trustedcomputinggroup.org/2010/IFMAP/2")
    protected PurgePublisherRequestType purgePublisher;
    @XmlElement(namespace = "http://www.trustedcomputinggroup.org/2010/IFMAP/2")
    protected AttachSession attachSession;
    @XmlElement(namespace = "http://www.trustedcomputinggroup.org/2010/IFMAP/2")
    protected RenewSessionType renewSession;
    @XmlElement(namespace = "http://www.trustedcomputinggroup.org/2010/IFMAP/2")
    protected EndSessionType endSession;
    @XmlElement(namespace = "http://www.trustedcomputinggroup.org/2010/IFMAP/2")
    protected ResponseType response;
    @XmlElement(namespace = "http://www.trustedcomputinggroup.org/2010/IFMAP/2")
    protected DumpRequestType dump;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the newSession property.
     * 
     * @return
     *     possible object is
     *     {@link NewSessionRequestType }
     *     
     */
    public NewSessionRequestType getNewSession() {
        return newSession;
    }

    /**
     * Sets the value of the newSession property.
     * 
     * @param value
     *     allowed object is
     *     {@link NewSessionRequestType }
     *     
     */
    public void setNewSession(NewSessionRequestType value) {
        this.newSession = value;
    }

    /**
     * Gets the value of the publish property.
     * 
     * @return
     *     possible object is
     *     {@link PublishRequestType }
     *     
     */
    public PublishRequestType getPublish() {
        return publish;
    }

    /**
     * Sets the value of the publish property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublishRequestType }
     *     
     */
    public void setPublish(PublishRequestType value) {
        this.publish = value;
    }

    /**
     * Gets the value of the search property.
     * 
     * @return
     *     possible object is
     *     {@link SearchRequestType }
     *     
     */
    public SearchRequestType getSearch() {
        return search;
    }

    /**
     * Sets the value of the search property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchRequestType }
     *     
     */
    public void setSearch(SearchRequestType value) {
        this.search = value;
    }

    /**
     * Gets the value of the subscribe property.
     * 
     * @return
     *     possible object is
     *     {@link SubscribeRequestType }
     *     
     */
    public SubscribeRequestType getSubscribe() {
        return subscribe;
    }

    /**
     * Sets the value of the subscribe property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubscribeRequestType }
     *     
     */
    public void setSubscribe(SubscribeRequestType value) {
        this.subscribe = value;
    }

    /**
     * Gets the value of the poll property.
     * 
     * @return
     *     possible object is
     *     {@link PollRequestType }
     *     
     */
    public PollRequestType getPoll() {
        return poll;
    }

    /**
     * Sets the value of the poll property.
     * 
     * @param value
     *     allowed object is
     *     {@link PollRequestType }
     *     
     */
    public void setPoll(PollRequestType value) {
        this.poll = value;
    }

    /**
     * Gets the value of the purgePublisher property.
     * 
     * @return
     *     possible object is
     *     {@link PurgePublisherRequestType }
     *     
     */
    public PurgePublisherRequestType getPurgePublisher() {
        return purgePublisher;
    }

    /**
     * Sets the value of the purgePublisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link PurgePublisherRequestType }
     *     
     */
    public void setPurgePublisher(PurgePublisherRequestType value) {
        this.purgePublisher = value;
    }

    /**
     * Gets the value of the attachSession property.
     * 
     * @return
     *     possible object is
     *     {@link AttachSession }
     *     
     */
    public AttachSession getAttachSession() {
        return attachSession;
    }

    /**
     * Sets the value of the attachSession property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttachSession }
     *     
     */
    public void setAttachSession(AttachSession value) {
        this.attachSession = value;
    }

    /**
     * Gets the value of the renewSession property.
     * 
     * @return
     *     possible object is
     *     {@link RenewSessionType }
     *     
     */
    public RenewSessionType getRenewSession() {
        return renewSession;
    }

    /**
     * Sets the value of the renewSession property.
     * 
     * @param value
     *     allowed object is
     *     {@link RenewSessionType }
     *     
     */
    public void setRenewSession(RenewSessionType value) {
        this.renewSession = value;
    }

    /**
     * Gets the value of the endSession property.
     * 
     * @return
     *     possible object is
     *     {@link EndSessionType }
     *     
     */
    public EndSessionType getEndSession() {
        return endSession;
    }

    /**
     * Sets the value of the endSession property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndSessionType }
     *     
     */
    public void setEndSession(EndSessionType value) {
        this.endSession = value;
    }

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseType }
     *     
     */
    public ResponseType getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseType }
     *     
     */
    public void setResponse(ResponseType value) {
        this.response = value;
    }

    /**
     * Gets the value of the dump property.
     * 
     * @return
     *     possible object is
     *     {@link DumpRequestType }
     *     
     */
    public DumpRequestType getDump() {
        return dump;
    }

    /**
     * Sets the value of the dump property.
     * 
     * @param value
     *     allowed object is
     *     {@link DumpRequestType }
     *     
     */
    public void setDump(DumpRequestType value) {
        this.dump = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
